import { ArrowRight, Check, ChevronRight, CircleHelp, LockKeyhole, Menu, Scale, ShieldCheck, Sparkles, X } from 'lucide-react';
import { useState } from 'react';
import './marketing.css';

const faqs = [
  ['Does KORA see my bid?', 'No. The bid value and witness remain on your device. KORA only receives a public proof outcome when the configured Midnight circuit is submitted.'],
  ['What becomes public?', 'The auction ID, eligibility result, a one-time nullifier, and a network transaction ID after a real submission.'],
  ['What does Gemini receive?', 'Only redacted public auction-policy text and labels. Never bids, wallet addresses, identity, secrets, or credentials.'],
];
export function Marketing() {
  const [open, setOpen] = useState<number | null>(null); const [menu, setMenu] = useState(false);
  const toAuction = () => { window.history.pushState({}, '', '/auction'); window.dispatchEvent(new Event('kora:navigate')); };
  return <main className="site"><header className="site-nav"><a className="brand" href="/"><span className="brand-mark">K</span><span>KORA</span></a><nav className={menu ? 'site-links show' : 'site-links'}><a href="#how">How it works</a><a href="#privacy">Privacy model</a><a href="#faq">FAQ</a><button className="nav-cta" onClick={toAuction}>Enter auction <ArrowRight size={15}/></button></nav><button className="menu" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">{menu ? <X/> : <Menu/>}</button></header>
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="pulse"/> Midnight sealed-bid auctions</p><h1>Bid with conviction.<br/><em>Reveal nothing extra.</em></h1><p className="lede">KORA lets collectors and procurement teams prove a bid meets a public rule—without broadcasting the number, the bidder, or the private witness behind it.</p><div className="hero-actions"><button className="primary" onClick={toAuction}>Explore Sankofa 01 <ArrowRight size={17}/></button><a href="#privacy" className="text-link">See the privacy boundary <ChevronRight size={16}/></a></div><div className="proof-stats"><div><b>0</b><span>bid values stored</span></div><div><b>1</b><span>proof per nullifier</span></div><div><b>∞</b><span>verifiable receipts</span></div></div></div><div className="hero-proof"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="proof-card"><div className="card-title"><LockKeyhole size={17}/><span>Bidder capsule</span><small>LOCAL</small></div><div className="private-line"><span>Bid amount</span><b>••••••••</b></div><div className="private-line"><span>Witness</span><b>••••••••</b></div><div className="proof-arrow"><ArrowRight size={18}/></div><div className="proof-output"><Check size={18}/><div><span>Public outcome</span><b>Eligible</b></div></div></div><p>Only the outcome crosses the boundary.</p></div></section>
    <section className="marquee"><span>PRIVATE BY DEFAULT</span><i/> <span>VERIFIABLE BY DESIGN</span><i/> <span>ONE BID, ONE PROOF</span><i/> <span>PRIVATE BY DEFAULT</span></section>
    <section id="how" className="section journey"><div className="section-intro"><p className="eyebrow">A bidder journey, not a crypto obstacle course</p><h2>Four deliberate steps.<br/>One protected bid.</h2></div><div className="journey-grid">{[['01','Read the public rule','Know the reserve, deadline, and exactly what the verifier needs.'],['02','Seal locally','Create a device-only commitment. The amount never enters KORA’s public service.'],['03','Review disclosure','See the protected and public sides before your wallet is asked to do anything.'],['04','Prove & submit','1AM submits the real circuit. A receipt appears only after the network responds.']].map(([n,t,d])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p><span><ArrowRight size={16}/></span></article>)}</div></section>
    <section className="auction-band"><div><p className="eyebrow">Live example</p><h2>Sankofa 01<br/><em>Sealed auction</em></h2><p>Reserve requirement ≥ 5,000 tDUST · closes in 03:18:42</p></div><div className="auction-points"><span><Check size={16}/> Public requirement loaded</span><span><Check size={16}/> Proof policy ready</span><span><Check size={16}/> Preview network available</span></div><button className="primary" onClick={toAuction}>Open bidder console <ArrowRight size={17}/></button></section>
    <section id="privacy" className="section privacy-section"><div className="section-intro"><p className="eyebrow">The deal is visible before you sign it</p><h2>Your privacy boundary<br/>is a product surface.</h2><p>No vague claims. KORA names what remains protected, what is published, and why every disclosed value exists.</p></div><div className="privacy-stack"><div className="privacy-panel private"><div><LockKeyhole size={19}/><span>Kept on your device</span></div><b>Bid amount</b><b>Bidder identity</b><b>Private witness & secret</b></div><div className="privacy-panel public"><div><ShieldCheck size={19}/><span>Publicly verifiable</span></div><b>Eligibility outcome</b><b>One-time nullifier</b><b>Final transaction ID</b></div><p><Scale size={17}/> A nullifier is disclosed only to prevent replay; it does not reveal the private witness that created it.</p></div></section>
    <section className="section intelligence"><div className="ai-orb"><Sparkles size={30}/></div><div><p className="eyebrow">Public-policy assistant</p><h2>Useful intelligence.<br/>No private context.</h2><p>Gemini turns a public auction rule into plain-language proof guidance. Redaction happens before the request; Pydantic validates the response; a deterministic local plan keeps the experience useful if Gemini is unavailable.</p><ul><li><Check size={16}/> Public policy labels only</li><li><Check size={16}/> Structured, validated output</li><li><Check size={16}/> Safe local fallback</li></ul></div></section>
    <section id="faq" className="section faq"><div className="section-intro"><p className="eyebrow">Questions worth asking</p><h2>Make the proof legible.</h2></div><div className="faq-list">{faqs.map(([q,a],i)=><article key={q}><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}><span><CircleHelp size={18}/>{q}</span><ChevronRight className={open===i?'rotate':''} size={19}/></button>{open===i&&<p>{a}</p>}</article>)}</div></section>
    <section className="final-cta"><p className="eyebrow">Ready when your wallet is</p><h2>Make your next bid<br/><em>private by default.</em></h2><button className="primary" onClick={toAuction}>Enter Sankofa 01 <ArrowRight size={17}/></button></section>
    <footer><div className="brand"><span className="brand-mark">K</span><span>KORA</span></div><span>Private auction infrastructure for Midnight.</span><button className="footer-link" onClick={toAuction}>Bidder console <ArrowRight size={14}/></button></footer>
  </main>;
}
